[colors]
foreground = "#bbbac1"
background = "#1e1d1c"
cursor_bg = "#bbbac1"
cursor_border = "#bbbac1"
cursor_fg = "#1e1d1c"
selection_bg = "#383737"
selection_fg = "#bbbac1"
split = "#6a6a6a"
compose_cursor = "#cfa991"
scrollbar_thumb = "#6a6a6a"

ansi = ["#121110", "#d67287", "#8ab56d", "#ebc686", "#a2bafa", "#9b9af5", "#e8a85f", "#bbbac1"]
brights = ["#6a6a6a", "#d67287", "#8ab56d", "#ebc686", "#a2bafa", "#ebabd5", "#e8a85f", "#bbbac1"]

[colors.tab_bar]
inactive_tab_edge = "#6a6a6a"
background = "#1e1d1c"

[colors.tab_bar.active_tab]
fg_color = "#9b9af5"
bg_color = "#383737"

[colors.tab_bar.inactive_tab]
fg_color = "#6a6a6a"
bg_color = "${inactive}"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#6a6a6a"
bg_color = "${inactive}"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#9b9af5"
bg_color = "#383737"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#9b9af5"
bg_color = "#1e1d1c"

[metadata]
aliases = []
author = "Casey Miller"
name = "coffeecat"