[colors]
foreground = "#bbbac1"
background = "#181b1b"
cursor_bg = "#bbbac1"
cursor_border = "#bbbac1"
cursor_fg = "#181b1b"
selection_bg = "#313b35"
selection_fg = "#bbbac1"
split = "#7a8478"
compose_cursor = "#e69875"
scrollbar_thumb = "#7a8478"

ansi = ["#111312", "#e67e80", "#7da77e", "#dbbc7f", "#a7c080", "#abbceb", "#78b0a8", "#bbbac1"]
brights = ["#7a8478", "#e67e80", "#7da77e", "#dbbc7f", "#a7c080", "#9094de", "#78b0a8", "#bbbac1"]

[colors.tab_bar]
inactive_tab_edge = "#7a8478"
background = "#181b1b"

[colors.tab_bar.active_tab]
fg_color = "#d6a56f"
bg_color = "#313b35"

[colors.tab_bar.inactive_tab]
fg_color = "#7a8478"
bg_color = "#1e2323"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#7a8478"
bg_color = "#1e2323"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#d6a56f"
bg_color = "#313b35"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#d6a56f"
bg_color = "#181b1b"

[metadata]
aliases = []
author = "Casey Miller"
name = "darkforest"