[colors]
foreground = "#bbbac1"
background = "#1b1c1d"
# background = "#161617" # alternate, darker bg
cursor_bg = "#bbbac1"
cursor_border = "#767777"
cursor_fg = "#1b1c1d"
selection_bg = "#323334"
selection_fg = "#bbc7b1"
split = "#767777"
compose_cursor = "#a69e6f"
scrollbar_thumb = "#222324"

ansi = ["#767777", "#9e5560", "#72966c", "#a2ad7b", "#50616F", "#8B7177", "#5B6078", "#7B7B7F"]
brights = ["#767777", "#b08c7d", "#8bab85", "#bbc7b1", "#748fa6", "#d6a9b3", "#868db5", "#bbbac1"]

[colors.tab_bar]
inactive_tab_edge = "#7B7B7F"
background = "#1b1c1d"

[colors.tab_bar.active_tab]
fg_color = "#a69e6f"
bg_color = "#323334"

[colors.tab_bar.inactive_tab]
fg_color = "#767777"
bg_color = "#222324"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#767777"
bg_color = "#222324"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#a69e6f"
bg_color = "#323334"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#a69e6f"
bg_color = "#1b1c1d"

[metadata]
aliases = []
name = "GYOKURO"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/wezterm/gyokuro.toml"
author = "Casey Miller"
