[colors]
foreground = "#bbbac1"
background = "#171719"
cursor_bg = "#bbbac1"
cursor_border = "#bbbac1"
cursor_fg = "#171719"
selection_bg = "#333336"
selection_fg = "#bbbac1"
split = "#555568"
compose_cursor = "#e3a462"
scrollbar_thumb = "#555568"

ansi = ["#2d2d2f", "#e67e80", "#7da77e", "#dbbc8a", "#86a3f0", "#8a88db", "#559ba3", "#bbbac1"]
brights = ["#555568", "#e67e80", "#7da77e", "#dbbc8a", "#86a3f0", "#e89bce", "#559ba3", "#bbbac1"]

[colors.tab_bar]
inactive_tab_edge = "#555568"
background = "#171719"

[colors.tab_bar.active_tab]
fg_color = "#abbceb"
bg_color = "#333336"

[colors.tab_bar.inactive_tab]
fg_color = "#555568"
bg_color = "#1d1d22"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#555568"
bg_color = "#1d1d22"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#abbceb"
bg_color = "#333336"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#abbceb"
bg_color = "#171719"

[metadata]
aliases = []
author = "Casey Miller"
name = "iceclimber"