[colors]
foreground = "#afafdd"
background = "#121315"
cursor_bg = "#afafdd"
cursor_border = "#afafdd"
cursor_fg = "#121315"
selection_bg = "#1d1f26"
selection_fg = "#afafdd"
split = "#666a82"
compose_cursor = "#e3a1ab"
scrollbar_thumb = "#666a82"

ansi = ["#111111", "#c76f82", "#9bbdb8", "#d2af98", "#95b1fc", "#9b9af5", "#a3849b", "#afafdd"]
brights = ["#666a82", "#c76f82", "#9bbdb8", "#d2af98", "#95b1fc", "#ad82a2", "#a3849b", "#afafdd"]

[colors.tab_bar]
inactive_tab_edge = "#666a82"
background = "#121315"

[colors.tab_bar.active_tab]
fg_color = "#688cb3"
bg_color = "#1d1f26"

[colors.tab_bar.inactive_tab]
fg_color = "#666a82"
bg_color = "#16171b"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#666a82"
bg_color = "#16171b"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#688cb3"
bg_color = "#1d1f26"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#688cb3"
bg_color = "#121315"

[metadata]
aliases = []
author = "Casey Miller"
name = "roseprime"