# ROSEPRIME Alacritty Colors
# Default colors
[colors.primary]
background = '#121315'
foreground = '#adadcc'

#[colors.cursor]
#cursor = '#adadcc'
#text = '#121315'

# Normal colors
[colors.normal]
black = '#111111'
red = '#c76f82'
green = '#9bbdb8'
yellow = '#d2af98'
blue = '#95b1fc'
magenta = '#9b9af5'
cyan = '#a3849b'
white = '#afafdd'

# Bright colors
[colors.bright]
black = '#666a82'
red = '#c76f82'
green = '#9bbdb8'
yellow = '#d2af98'
blue = '#95b1fc'
magenta = '#ad82a2'
cyan = '#a3849b'
white = '#afafdd'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e3a1ab'

[[colors.indexed_colors]]
index = 17
color = '#9b9af5'
