  # Theme: darkforest
  # URL: https://github.com/cdmill/neomodern.nvim/raw/main/extras/yazi/darkforest.toml

  [manager]
  cwd = { fg = "#a7c080" }

  hovered         = { fg = "#78b0a8", bg = "#1e2323" }
  preview_hovered = { fg = "#78b0a8", bg = "#1e2323" }

  find_keyword  = { fg = "#d6a56f", italic = true }
  find_position = { fg = "#d6a56f", bg = "reset", italic = true }

  marker_copied   = { fg = "#d6a56f" }
  marker_cut      = { fg = "#e67e80" }
  marker_selected = { fg = "#d6a56f", bg = "#313b35" }

  tab_active   = { fg = "#d6a56f", bg = "#313b35" }
  tab_inactive = { fg = "#7a8478", bg = "#313b35" }
  tab_width    = 1

  count_cut      = { fg = "#d6a56f", bg = "#1e2323" }
  count_copied   = { fg = "#d6a56f", bg = "#1e2323" }
  count_selected = { fg = "#d6a56f", bg = "#1e2323" }

  border_symbol = "│"
  border_style  = { fg = "#7a8478" }

  [status]
  separator_open  = ""
  separator_close = ""
  separator_style = { fg = "#181b1b", bg = "#a7c080" }

  mode_normal = { fg = "#181b1b", bg = "#a7c080", bold = true }
  mode_select = { fg = "#181b1b", bg = "#c3c082", bold = true }
  mode_unset  = { fg = "#181b1b", bg = "#78b0a8", bold = true }

  progress_label  = { fg = "#d6a56f", bold = true }
  progress_normal = { fg = "#d6a56f", bg = "#313b35" }
  progress_error  = { fg = "#181b1b", bg = "#e67e80" }

  permissions_t = { fg = "#bbbac1" }
  permissions_r = { fg = "#dbbc7f" }
  permissions_w = { fg = "#e67e80" }
  permissions_x = { fg = "#a7c080" }
  permissions_s = { fg = "#c3c082" }

  [input]
  border   = { fg = "#7a8478" }
  title    = {}
  value    = {}
  selected = { reversed = true }

  [select]
  border   = { fg = "#7a8478" }
  active   = { fg = "#7da77e" }
  inactive = {}

  [tasks]
  border  = { fg = "#7a8478" }
  title   = {}
  hovered = { underline = true }

  [which]
  mask            = { bg = "#7da77e" }
  cand            = { fg = "#78b0a8" }
  rest            = { fg = "#e69875" }
  desc            = { fg = "#dbbc7f" }
  separator       = "  "
  separator_style = { fg = "#c3c082"}

  [help]
  on      = { fg = "#c76f82" }
  exec    = { fg = "#e69875" }
  desc    = { fg = "#dbbc7f" }
  hovered = { bg = "#78b0a8", bold = true }
  footer  = { fg = "#7a8478", bg = "#1e2323" }

  [filetype]
  rules = [
    # Media
    { mime = "image/*", fg = "#c76f82"},
    { mime = "{audio,video}/*", fg = "#dbbc7f"},

    # Archives
    { mime = "application/{,g}zip", fg = "#e67e80"},
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80"},

    # Fallback
    { name = "*", fg = "#bbbac1"},
    { name = "*/", fg = "#a7c080"}
  ]
  