  # Theme: iceclimber
  # URL: https://github.com/cdmill/neomodern.nvim/raw/main/extras/yazi/iceclimber.toml

  [manager]
  cwd = { fg = "#cc93b8" }

  hovered         = { fg = "#629da3", bg = "#1d1d22" }
  preview_hovered = { fg = "#629da3", bg = "#1d1d22" }

  find_keyword  = { fg = "#abbceb", italic = true }
  find_position = { fg = "#abbceb", bg = "reset", italic = true }

  marker_copied   = { fg = "#6b6b99" }
  marker_cut      = { fg = "${error}" }
  marker_selected = { fg = "#abbceb" }

  tab_active   = { fg = "#cc93b8", bg = "#2a2a31" }
  tab_inactive = { fg = "#555568", bg = "#2a2a31" }
  tab_width    = 1

  count_cut      = { fg = "#abbceb", bg = "#1d1d22" }
  count_copied   = { fg = "#abbceb", bg = "#1d1d22" }
  count_selected = { fg = "#abbceb", bg = "#1d1d22" }

  border_symbol = "│"
  border_style  = { fg = "#555568" }

  [mode]
  normal_main   = { fg = "#171719", bg = "#86a3f0", bold = true }
  normal_alt    = { fg = "#171719", bg = "#86a3f0", bold = true }
  select_main   = { fg = "#171719", bg = "#8a88db", bold = true }
  select_alt    = { fg = "#171719", bg = "#8a88db", bold = true }
  unset_main    = { fg = "#171719", bg = "#6b6b99", bold = true }
  unset_alt     = { fg = "#171719", bg = "#6b6b99", bold = true }

  [status]
  separator_open  = ""
  separator_close = ""
  separator_style = { fg = "#2a2a31", bg = "#2a2a31" }

  progress_label  = { fg = "#abbceb", bold = true }
  progress_normal = { fg = "#abbceb", bg = "#2a2a31" }
  progress_error  = { fg = "#171719", bg = "${error}" }

  permissions_t = { fg = "#bbbac1" }
  permissions_r = { fg = "#cc93b8" }
  permissions_w = { fg = "#e67e80" }
  permissions_x = { fg = "#86a3f0" }
  permissions_s = { fg = "#9b99a3" }

  [input]
  border   = { fg = "#555568" }
  title    = {}
  value    = {}
  selected = { reversed = true }

  [select]
  border   = { fg = "#555568" }
  active   = { fg = "#8a88db" }
  inactive = {}

  [tasks]
  border  = { fg = "#555568" }
  title   = {}
  hovered = { underline = true }

  [which]
  mask            = { bg = "#151517" }
  cand            = { fg = "#629da3" }
  rest            = { fg = "#a8a6de" }
  desc            = { fg = "#6b6b99" }
  separator       = "  "
  separator_style = { fg = "#9b99a3"}

  [help]
  on      = { fg = "#a8a6de" }
  run    = { fg = "#6b6b99" }
  desc    = { fg = "#555568" }
  hovered = { fg = "#629da3", bg = "#1d1d22", bold = true }
  footer  = { fg = "#555568", bg = "#1d1d22" }

  [filetype]
  rules = [
    # Media
    { mime = "image/*", fg = "#a8a6de"},
    { mime = "{audio,video}/*", fg = "#6b6b99"},

    # Archives
    { mime = "application/{,g}zip", fg = "#e67e80"},
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80"},

    # Fallback
    { name = "*", fg = "#bbbac1"},
    { name = "*/", fg = "#cc93b8"}
  ]
  